package io.github.coenraadhuman.business.rule.engine.implementation.common;

public enum TestResponse {
    TEST_VALIDATION_IMMEDIATE_INVALID_RULE,
    TEST_VALIDATION_IMMEDIATE_INVALID_CHILD_RULE,
    TEST_VALIDATION_DEFERRED_INVALID_CHILD_RULE,
    TEST_VALIDATION_NOT_APPLICABLE_RULE,
    TEST_VALIDATION_NOT_APPLICABLE_CHILD_RULE,
    TEST_VALIDATION_VALID_RULE,
    TEST_VALIDATION_VALID_CHILD_RULE,
    TEST_VALIDATION_PROVIDER_VALID_RULE,
    TEST_VALIDATION_PROVIDER_IMMEDIATE_INVALID_CHILD_RULE,
    TEST_VALIDATION_PROVIDER_DEFERRED_INVALID_CHILD_RULE,

    TEST_VALIDATION_PROVIDER_VALID_DATA_CHILD_RULE,

    VALID_DATA_RETRIEVER,
    IMMEDIATE_INVALID_DATA_RETRIEVER,
    DEFERRED_INVALID_DATA_RETRIEVER
}
